name: wake_senpai
description: "WakeSenpai - Jam Alarm Anime Offline"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.1.0
  flutter_local_notifications: ^12.0.4
  android_alarm_manager_plus: ^2.1.4
  just_audio: ^0.9.46
  sensors_plus: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/tflite/