name: WakeSenpai Beta Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Beta APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Beta APK
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload Beta APK
      uses: actions/upload-artifact@v4
      with:
        name: wake_senpai_beta_apk
        path: build/app/outputs/flutter-apk/app-release.apk


